import {reviewInstructions,businessData,normalizeReview} from '../app/review-model';
import {stages,type Plan} from '../app/model';
export const config={maxDuration:60};
export async function POST(request:Request){
 const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
 const origin=request.headers.get('origin');if(origin&&new URL(request.url).origin!==origin)return json({error:'Origem não autorizada.'},403);
 const key=request.headers.get('x-provider-key');if(!key||key.length<15||key.length>512)return json({error:'Conecte uma chave de API válida.'},401);
 try{const raw=await request.text();if(raw.length>160000)return json({error:'Plano muito grande para esta avaliação.'},413);const body=JSON.parse(raw);if(!['openai','anthropic'].includes(body.provider)||typeof body.model!=='string'||!/^[a-zA-Z0-9._:-]{1,100}$/.test(body.model)||!Number.isInteger(body.scope)||body.scope< -1||body.scope>6||!body.plan||typeof body.plan!=='object')return json({error:'Parâmetros inválidos.'},400);
 const plan:Plan=Object.fromEntries(Object.entries(body.plan).filter(([,v])=>typeof v==='string')) as Plan;const data=businessData(plan);if(Object.values(data).some(v=>v.length>12000))return json({error:'Reduza cada campo para até 12.000 caracteres.'},413);
 const input=JSON.stringify({scope:body.scope<0?'final':stages[body.scope].name,stages:stages.map((s,i)=>({index:i,name:s.name,fields:s.fields.map(f=>({key:f[0],label:f[1]}))})),business:data});
 const isOpenAI=body.provider==='openai';const upstream=await fetch(isOpenAI?'https://api.openai.com/v1/responses':'https://api.anthropic.com/v1/messages',{method:'POST',headers:isOpenAI?{'Content-Type':'application/json',Authorization:`Bearer ${key}`}:{'Content-Type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify(isOpenAI?{model:body.model,instructions:reviewInstructions,input,max_output_tokens:5000,store:false,text:{format:{type:'json_object'}}}:{model:body.model,system:reviewInstructions,max_tokens:5000,messages:[{role:'user',content:input}]}),signal:AbortSignal.timeout(50000)});
 if(!upstream.ok){const code=upstream.status;return json({error:code===401?'Chave recusada pelo provedor.':code===429?'Limite ou saldo de API indisponível.':code===404?'Modelo não encontrado. Confira o ID na sua conta.':'O provedor não concluiu a avaliação. Confira modelo, chave e saldo.'},code>=500?502:code)}
 const answer=await upstream.json();const text=isOpenAI?(answer.output||[]).flatMap((o:{content?:{type:string;text?:string}[]})=>o.content||[]).filter((c:{type:string})=>c.type==='output_text').map((c:{text:string})=>c.text).join(''):(answer.content||[]).filter((c:{type:string})=>c.type==='text').map((c:{text:string})=>c.text).join('');const clean=text.trim().replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,'');const review=normalizeReview(JSON.parse(clean),body.scope,plan,isOpenAI?'OpenAI':'Claude');return json({review});
 }catch(e){return json({error:e instanceof Error&&e.name==='TimeoutError'?'A avaliação demorou demais. Tente novamente.':'Não foi possível concluir uma avaliação válida. Revise a conexão e tente novamente.'},502)}
}
